export default [
    /*Repertoire des entreprises RDc à 2018*/
    {
      type: "Privé",
      nom : "AFRILAND FIRST BANK",
      ville  : "KInshasa"
    },
    {type: "Privé", nom:'BANQUE COMMERCIALE DU CONGO SARL',ville:"Kinshasa"},
    {type: "Privé", nom:'AMB MINING SPRL',ville:"Kinshasa"},
    {type: "Privé", nom:'ASHANTI GOLDFIELD KILO SARL',ville:"Kinshasa"},
    {type: "Privé", nom:'BANQUE INTERNATIONALE DE CREDIT BIC SARL',ville:"Kinshasa"},
    {type: "Privé", nom:'BANRO SARL',ville:"Kinshasa"},
    {type: "Privé", nom:'BAT CONGO SARL',ville:"Kinshasa"},
    {type: "Privé", nom:'BELTEXCO',ville:"Kinshasa"},
    {type: "Privé", nom:'BHP BILLITON',ville:"Kinshasa"},
    {type: "Privé", nom:'BIAC',ville:"Kinshasa"},
    {type: "Privé", nom:'BRACONGO',ville:"Kinshasa"},
    {type: "Privé", nom:'BRALIMA',ville:"Kinshasa"},
    {type: "Privé", nom:'CILU SARL',ville:"Kinshasa"},
    {type: "Privé", nom:'CITIGROUP',ville:"Kinshasa"},
    {type: "Privé", nom:'CONGO FUTUR SPRL',ville:"Kinshasa"},
    {type: "Privé", nom:'CONGOTEX SPRL',ville:"Kinshasa"},
    {type: "Privé", nom:'DCP SARL',ville:"Kinshasa"},
    {type: "Privé", nom:'DOVER COSMETICS ',ville:"Kinshasa"},
    {type: "Privé", nom:'LEDYA SPRL',ville:"Kinshasa"},
    {type: "Privé", nom:'MAFRICOM SPRL',ville:"Kinshasa"},
    {type: "Privé", nom:'MAGENERGY CONGO SPRL',ville:"Kinshasa"},
    {type: "Privé", nom:'MARSAVCO SARL',ville:"Kinshasa"},
    {type: "Privé", nom:'MIDEMA SARL',ville:"Kinshasa"},
    {type: "Privé", nom:'ORGAMAN SPRL',ville:"Kinshasa"},
    {type: "Privé", nom:'PERENCOREP SPRL',ville:"Kinshasa"},
    {type: "Privé", nom:'RAWBANK SARL',ville:"Kinshasa"},
    {type: "Privé", nom:'SAM METAL SPRL',ville:"Lubumbashi"},
    {type: "Privé", nom:'SEP CONGO SARL',ville:"Kinshasa"},
    {type: "Privé", nom:'SESOMO',ville:"Kinshasa"},
    {type: "Privé", nom:'SN BRUSSELS AIRLINES',ville:"Kinshasa"},
    {type: "Privé", nom:'SOCIMEX',ville:"Kinshasa"},
    {type: "Privé", nom:'SOCIR SARL',ville:"Kinshasa"},
    {type: "Privé", nom:'SOFICOM SPRL',ville:"Kinshasa"},
    {type: "Privé", nom:'SOMIKA',ville:"Lubumbashi"},
    {type: "Privé", nom:'TRUST MERCHANT BANK',ville:"Lubumbashi"},
    {type: "Privé", nom:'VODACOM',ville:"Kinshasa"},
    {type: "Privé", nom:'AGETRAF SDV SARL',ville:"Kinshasa"},
    {type: "Privé", nom:'ATC SARL',ville:"Kinshasa"},
    {type: "Privé", nom:'BANQUE CONGOLAISE SARL',ville:"Kinshasa"},
    {type: "Privé", nom:'BORGAKIM MINING SPRL',ville:"Kinshasa"},
    {type: "Privé", nom:'CAA',ville:"Kinshasa"},
    {type: "Privé", nom:'CFAO',ville:"Kinshasa"},
    {type: "Privé", nom:'CHANIMETAL SARL',ville:"Kinshasa"},
    {type: "Privé", nom:'COBIL SARL',ville:"Kinshasa"},
    {type: "Privé", nom:'COBRA',ville:"Kinshasa"},
    {type: "Privé", nom:'CONGO DIAM SPRL',ville:"Kinshasa"},
    {type: "Privé", nom:'CONGO OIL',ville:"Kinshasa"},
    {type: "Privé", nom:'COTRACO',ville:"Kinshasa"},
    {type: "Privé", nom:'DE BEERS SPRL',ville:"Kinshasa"},
    {type: "Privé", nom:'DHL',ville:"Kinshasa"},
    {type: "Privé", nom:'DISPROMALT SPRL',ville:"Kinshasa"},
    {type: "Privé", nom:'ELF/SCP',ville:"Kinshasa"},
    {type: "Privé", nom:'EMAXON',ville:"Kinshasa"},
    {type: "Privé", nom:'FEMCO',ville:"Kinshasa"},
    {type: "Privé", nom:'FINA CONGO',ville:"Kinshasa"},
    {type: "Privé", nom:'GECOTRANS SPRL',ville:"Kinshasa"},
    {type: "Privé", nom:'GENERALCO SPRL',ville:"Kinshasa"},
    {type: "Privé", nom:'GHANDOUR INDUSTRIE',ville:"Kinshasa"},
    {type: "Privé", nom:'GRAND HOTEL KINSHASA ',ville:"Kinshasa"},
    {type: "Privé", nom:'HASSON & FRERES SPRL',ville:"Kinshasa"},
    {type: "Privé", nom:'HOTEL MEMLING',ville:"Kinshasa"},
    {type: "Privé", nom:'INALCA',ville:"Kinshasa"},
    {type: "Privé", nom:'MAERSK RDC',ville:"Kinshasa"},
    {type: "Privé", nom:'MARGAUX',ville:"Kinshasa"},
    {type: "Privé", nom:'MILLENIUM SPRL ',ville:"Kinshasa"},
    {type: "Privé", nom:'MINOCONGO',ville:"Kinshasa"},
    {type: "Privé", nom:'NESTLE',ville:"Kinshasa"},
    {type: "Privé", nom:'NOVA PRODUCT SPRL',ville:"Kinshasa"},
    {type: "Privé", nom:'PARISI',ville:"Kinshasa"},
    {type: "Privé", nom:'PLASTICA',ville:"Kinshasa"},
    {type: "Privé", nom:'PREMIUM FOOD',ville:"Kinshasa"},
    {type: "Privé", nom:'PROMIGEM',ville:"Kinshasa"},
    {type: "Privé", nom:'SIFORCO SARL',ville:"Kinshasa"},
    {type: "Privé", nom:'SOCITRANS',ville:"Kinshasa"},
    {type: "Privé", nom:'SOKIN',ville:"Lubumbashi"},
    {type: "Privé", nom:'STANBIC BANK CONGO SARL',ville:"Kinshasa"},
    {type: "Privé", nom:'TISSAKIN SARL',ville:"Kinshasa"},
    {type: "Privé", nom:'TRACTAFRIC',ville:"Kinshasa"},
    {type: "Privé", nom:'TRANSBENZ ',ville:"Kinshasa"},
    {type: "Privé", nom:'TRANS GAZELLE',ville:"Kinshasa"},
    {type: "Privé", nom:'TRANS M',ville:"Kinshasa"},
    {type: "Privé", nom:'TRANSMAC SPRL',ville:"Kinshasa"},
    {type: "Privé", nom:'UTEXAFRICA',ville:"Kinshasa"},
    {type: "Privé", nom:'AAA',ville:"Kinshasa"},
    {type: "Privé", nom:'AFRICANUS SPRL',ville:"Kinshasa"},
    {type: "Privé", nom:'AFRINET',ville:"Kinshasa"},
    {type: "Privé", nom:'AFRITEC',ville:"Kinshasa"},
    {type: "Privé", nom:'AGB',ville:"Kinshasa"},
    {type: "Privé", nom:'AGIKIN SPRL',ville:"Kinshasa"},
    {type: "Privé", nom:'AJM & ASSOCIATES SPRL',ville:"Kinshasa"},
    {type: "Privé", nom:'ALLGLASS',ville:"Kinshasa"},
    {type: "Privé", nom:'ASEM SPRL',ville:"Kinshasa"},
    {type: "Privé", nom:'AVC',ville:"Kinshasa"},
    {type: "Privé", nom:'BACOM SPRL',ville:"Kinshasa"},
    {type: "Privé", nom:'BATIPONT',ville:"Kinshasa"},
    {type: "Privé", nom:'BARNET',ville:"Kinshasa"},
    {type: "Privé", nom:'BIA SPRL',ville:"Kinshasa"},


    {type: "Privé", nom:'BOUKIN ',ville:"Kinshasa"},
    {type: "Privé", nom:'BUROMECA SARL ',ville:"Kinshasa"},
    {type: "Privé", nom:'CAISA PHARMA INTER',ville:"Kinshasa"},
    {type: "Privé", nom:'CARRIGRES SARL',ville:"Kinshasa"},
    {type: "Privé", nom:'CARTOMO SPRL',ville:"Kinshasa"},
    {type: "Privé", nom:'CAUDITEC',ville:"Kinshasa"},
    {type: "Privé", nom:'COBEGA ',ville:"Kinshasa"},
    {type: "Privé", nom:'COMEXAS AFRIQUE',ville:"Kinshasa"},
    {type: "Privé", nom:'CONGO ASSURANCES & SERVICES MULTIPLES CIMS',ville:"Kinshasa"},
    {type: "Privé", nom:'CONGO STORE',ville:"Kinshasa"},
    {type: "Privé", nom:'DEMIMPEX AFRIQUE',ville:"Kinshasa"},
    {type: "Privé", nom:'DSA',ville:"Kinshasa"},
    {type: "Privé", nom:'DUTY FREE SHOP NDJILI DFSN SPRL',ville:"Kinshasa"},
    {type: "Privé", nom:'ELDIS CONGO',ville:"Kinshasa"},
    {type: "Privé", nom:'ELIT',ville:"Kinshasa"},
    {type: "Privé", nom:'ENTREPRISES DE COCK SPRL',ville:"Kinshasa"},
    {type: "Privé", nom:' ERICSSON ',ville:"Kinshasa"},
    {type: "Privé", nom:'ESCOKIN',ville:"Kinshasa"},
    {type: "Privé", nom:'FALCOM SPRL',ville:"Kinshasa"},
    {type: "Privé", nom:'FIGEPAR',ville:"Kinshasa"},
    {type: "Privé", nom:'FILAIR SPRL',ville:"Kinshasa"},
    {type: "Privé", nom:'FRANCOPLAST',ville:"Kinshasa"},
    {type: "Privé", nom:'GAANA SPRL',ville:"Kinshasa"},
    {type: "Privé", nom:'GRAPHIC SYSTEMS',ville:"Kinshasa"},
    {type: "Privé", nom:'GROUPE 4 SECURICOR ',ville:"Kinshasa"},
    {type: "Privé", nom:'GROUPE MUKUTA TRADING (GMT) SPRL',ville:"Lubumbashi"},
    {type: "Privé", nom:'GTM SPRL',ville:"Kinshasa"},
    {type: "Privé", nom:'GTS',ville:"Kinshasa"},
    {type: "Privé", nom:'GURMEET',ville:"Kinshasa"},
    {type: "Privé", nom:'INTERCONNECT',ville:"Kinshasa"},
    {type: "Privé", nom:'IPS',ville:"Kinshasa"},
    {type: "Privé", nom:'ITB ',ville:"Kinshasa"},
    {type: "Privé", nom:'IVECO',ville:"Lubumbashi"},
    {type: "Privé", nom:'JCC & ASSOCIES',ville:"Lubumbashi"},
    {type: "Privé", nom:'JOB FACTORY ',ville:"Kinshasa"},
    {type: "Privé", nom:'JVL SCARL',ville:"Kinshasa"},
    {type: "Privé", nom:'KINFOOD',ville:"Kinshasa"},
    {type: "Privé", nom:'MAGENYA',ville:"Kinshasa"},
    {type: "Privé", nom:'MALILA AIRLIFT',ville:"Kinshasa"},
    {type: "Privé", nom:'MECOM PLUS SPRL',ville:"Kinshasa"},
    {type: "Privé", nom:'MICROCOM',ville:"Kinshasa"},
    {type: "Privé", nom:' MIDAS ',ville:"Kinshasa"},
    {type: "Privé", nom:'MISTER CASH TRANSFERT',ville:"Kinshasa"},
    {type: "Privé", nom:'NOCAFEX SPRL',ville:"Kinshasa"},
    {type: "Privé", nom:'PEGAL SPRL',ville:"Kinshasa"},
    {type: "Privé", nom:'PARCAFRICA',ville:"Kinshasa"},
    {type: "Privé", nom:'PELOUSTORE',ville:"Kinshasa"},
    {type: "Privé", nom:'PETROCOM',ville:"Kinshasa"},
    {type: "Privé", nom:'PHARMAGROS ',ville:"Kinshasa"},
    {type: "Privé", nom:'PHARMAKINA',ville:"Kinshasa"},
    {type: "Privé", nom:'PIRECO SPRL ',ville:"Kinshasa"},
    {type: "Privé", nom:'PLANTATION & HUILERIE DU CONGO PHC',ville:"Kinshasa"},
    {type: "Privé", nom:'PLASTINOVA',ville:"Kinshasa"},
    {type: "Privé", nom:'PLEXI LIGHT',ville:"Kinshasa"},
    {type: "Privé", nom:'PRICE WATERHOUSE',ville:"Kinshasa"},
    {type: "Privé", nom:'PRODIMPEX',ville:"Kinshasa"},
    {type: "Privé", nom:'PROMED',ville:"Kinshasa"},
    {type: "Privé", nom:'PUBLI INTER',ville:"Kinshasa"},
    {type: "Privé", nom:'PUBLI PAN',ville:"Kinshasa"},
    {type: "Privé", nom:'RAGA ',ville:"Kinshasa"},
    {type: "Privé", nom:'ROFFE CONGO',ville:"Kinshasa"},
    {type: "Privé", nom:'S2GI SARL',ville:"Kinshasa"},
    {type: "Privé", nom:'SAFBOIS',ville:"Kinshasa"},
    {type: "Privé", nom:'SAMKHA',ville:"Kinshasa"},
    {type: "Privé", nom:'SAVCOKI',ville:"Kinshasa"},
    {type: "Privé", nom:'SEBO SPRL',ville:"Kinshasa"},
    {type: "Privé", nom:'SECURICO',ville:"Kinshasa"},
    {type: "Privé", nom:'SEDAF SPRL',ville:"Kinshasa"},
    {type: "Privé", nom:'SHALINA SPRL',ville:"Kinshasa"},
    {type: "Privé", nom:'SICOBOIS SPRL',ville:"Kinshasa"},
    {type: "Privé", nom:'SIVOP SPRL',ville:"Kinshasa"},
    {type: "Privé", nom:'SOCIETE INDUSTRIELLE DES PLASTIQUES',ville:"Kinshasa"},
    {type: "Privé", nom:'SOFIDE SARL',ville:"Kinshasa"},
    {type: "Privé", nom:'SOGALKIN SPRL',ville:"Lubumbashi"},
    {type: "Public", nom:'SONAL SARL',ville:"Kinshasa"},
    {type: "Privé", nom:'TELETRON NEW',ville:"Kinshasa"},
    {type: "Privé", nom:'TFCE',ville:"Kinshasa"},
    {type: "Privé", nom:'UAC SPRL',ville:"Kinshasa"},
    {type: "Privé", nom:'UPAK SPRL',ville:"Kinshasa"},
    {type: "Privé", nom:'ZAHIRA SPRL',ville:"Kinshasa"},
    {type: "Privé", nom:'ZENUFA ',ville:"Kinshasa"},
    {type: "Privé", nom:'ABS',ville:"Kinshasa"},
    {type: "Privé", nom:'ACCAT Association',ville:"Kinshasa"},
    {type: "Privé", nom:'ACF',ville:"Kinshasa"},
    {type: "Privé", nom:'ACOKIN',ville:"Kinshasa"},
    {type: "Privé", nom:'AFB',ville:"Kinshasa"},
    {type: "Privé", nom:'AFRICA INDUSTRIES SPRL',ville:"Kinshasa"},
    {type: "Privé", nom:'AFUNET SPRL',ville:"Kinshasa"},
    {type: "Privé", nom:'AGAKARI SPRL',ville:"Kinshasa"},
    {type: "Privé", nom:'AIGLON',ville:"Kinshasa"},
    {type: "Privé", nom:'LIMENTATION JIJI',ville:"Kinshasa"},
    {type: "Privé", nom:'ALL PARTS',ville:"Kinshasa"},
    {type: "Privé", nom:'ALLIANCE CCC',ville:"Kinshasa"},
    {type: "Privé", nom:'ALPHA Ets.',ville:"Kinshasa"},
    {type: "Privé", nom:'AMA Ets',ville:"Kinshasa"},
    {type: "Privé", nom:'AMAR',ville:"Kinshasa"},
   
   
   
      
  ];
  
  
  
  
  
  
  